window.SEED = {
  designers: [
    { id: "o", initial: "O", name: "Ollie", color: "#f0b429" },
    { id: "b", initial: "B", name: "Benni", color: "#3aa0ff" },
    { id: "e", initial: "E", name: "Emily", color: "#8b7cff" },
    { id: "j", initial: "J", name: "Jason", color: "#3ee0c8" },
  ],
  items: [
    {
      id: "hist-marketplace-v2",
      title: "Historical Data Marketplace V2",
      tickets: "PR-1283 / Design-344",
      section: "immediate",
      assigneeId: "o",
      notes: "Already handed off to engineering.",
      bars: [
        {
          kind: "handed-off",
          label: "Already handed off to Dev",
          start: "2026-08-17",
          end: "2026-09-04",
        },
      ],
      milestones: [{ kind: "release", date: "2026-09-11", label: "Release 1.06" }],
    },
    {
      id: "future-marketplace",
      title: "Future Data Marketplace",
      tickets: "PR-1272 / Design-304",
      section: "immediate",
      assigneeId: "b",
      notes: "",
      bars: [
        {
          kind: "design",
          label: "Finalize Designs",
          start: "2026-08-17",
          end: "2026-08-28",
        },
        {
          kind: "engineering",
          label: "Engineering",
          start: "2026-08-31",
          end: "2026-09-11",
        },
      ],
      milestones: [
        { kind: "handoff", date: "2026-08-28", label: "Handoff to Dev" },
        { kind: "release", date: "2026-09-11", label: "Release 1.06" },
      ],
    },
    {
      id: "annual-discount",
      title: "50% Annual Plan Discount",
      tickets: "",
      section: "immediate",
      assigneeId: "o",
      notes: "",
      bars: [
        {
          kind: "design",
          label: "Finalize Designs",
          start: "2026-08-17",
          end: "2026-08-28",
        },
        {
          kind: "engineering",
          label: "Engineering",
          start: "2026-08-31",
          end: "2026-09-11",
        },
      ],
      milestones: [
        { kind: "handoff", date: "2026-08-28", label: "Handoff to Dev" },
        { kind: "release", date: "2026-09-11", label: "Release 1.06" },
      ],
    },
    {
      id: "seat-reallocation",
      title: "Seat Reallocation",
      tickets: "PR-1213 / Design-227",
      section: "immediate",
      assigneeId: "e",
      notes: "",
      bars: [
        {
          kind: "design",
          label: "Finalize Designs",
          start: "2026-08-17",
          end: "2026-08-28",
        },
        {
          kind: "engineering",
          label: "Engineering",
          start: "2026-08-31",
          end: "2026-09-11",
        },
      ],
      milestones: [
        { kind: "handoff", date: "2026-08-28", label: "Handoff to Dev" },
        { kind: "release", date: "2026-09-11", label: "Release 1.06" },
      ],
    },
    {
      id: "search-org-email",
      title: "Search Organization by Email",
      tickets: "",
      section: "immediate",
      assigneeId: "e",
      notes: "",
      bars: [
        {
          kind: "design",
          label: "Finalize Designs",
          start: "2026-08-24",
          end: "2026-09-04",
        },
        {
          kind: "engineering",
          label: "Engineering",
          start: "2026-09-07",
          end: "2026-09-18",
        },
      ],
      milestones: [
        { kind: "handoff", date: "2026-09-04", label: "Handoff to Dev" },
        { kind: "release", date: "2026-09-18", label: "Release 1.07" },
      ],
    },
    {
      id: "xenodata-report",
      title: "Xenodata Quarterly Report",
      tickets: "",
      section: "immediate",
      assigneeId: "e",
      notes: "",
      bars: [
        {
          kind: "design",
          label: "Design Creation and Approval",
          start: "2026-08-24",
          end: "2026-09-04",
        },
        {
          kind: "engineering",
          label: "Engineering",
          start: "2026-09-07",
          end: "2026-09-25",
        },
      ],
      milestones: [
        { kind: "handoff", date: "2026-09-04", label: "Handoff to Dev" },
        { kind: "release", date: "2026-09-25", label: "Release 1.07" },
      ],
    },
    {
      id: "more-analytics-charts",
      title: "More Analytics Charts",
      tickets: "",
      section: "immediate",
      assigneeId: "b",
      notes: "CAVE clickable mock. Works toward the Analytics bubble / more analytics chart work.",
      bars: [
        {
          kind: "research",
          label: "CAVE clickable mock",
          start: "2026-08-17",
          end: "2026-08-21",
        },
        {
          kind: "design",
          label: "Design Creation and Approval",
          start: "2026-08-24",
          end: "2026-09-04",
        },
        {
          kind: "engineering",
          label: "Engineering",
          start: "2026-09-07",
          end: "2026-09-25",
        },
      ],
      milestones: [
        { kind: "handoff", date: "2026-09-04", label: "Handoff to Dev" },
        { kind: "release", date: "2026-09-25", label: "Release 1.07" },
      ],
    },
    {
      id: "query-builder-results",
      title: "Query Builder Results",
      tickets: "",
      section: "immediate",
      assigneeId: "",
      notes: "",
      bars: [
        {
          kind: "research",
          label: "Research / alignment",
          start: "2026-08-17",
          end: "2026-08-28",
        },
        {
          kind: "design",
          label: "Design Creation and Approval",
          start: "2026-08-31",
          end: "2026-09-11",
        },
        {
          kind: "engineering",
          label: "Engineering",
          start: "2026-09-14",
          end: "2026-09-25",
        },
      ],
      milestones: [
        { kind: "handoff", date: "2026-09-11", label: "Handoff to Dev" },
        { kind: "release", date: "2026-09-25", label: "Release 1.07" },
      ],
    },
    {
      id: "analytics-suite-explore",
      title: "Analytics Suite Blue Sky Exploration",
      tickets: "",
      section: "explorations",
      assigneeId: "b",
      notes: "Feeds Analytics Report Builder in Q4.",
      bars: [
        {
          kind: "exploration",
          label: "Exploration",
          start: "2026-08-31",
          end: "2026-09-18",
        },
      ],
      milestones: [],
      dependsOn: [],
      feeds: ["analytics-report-builder"],
    },
    {
      id: "marketplace-explore",
      title: "Marketplace Blue Sky Exploration",
      tickets: "",
      section: "explorations",
      assigneeId: "o",
      notes: "",
      bars: [
        {
          kind: "exploration",
          label: "Exploration",
          start: "2026-09-07",
          end: "2026-09-25",
        },
      ],
      milestones: [],
    },
    {
      id: "full-portal-explore",
      title: "Full Portal Blue Sky Exploration",
      tickets: "",
      section: "explorations",
      assigneeId: "e",
      notes: "",
      bars: [
        {
          kind: "exploration",
          label: "Exploration",
          start: "2026-09-14",
          end: "2026-10-02",
        },
      ],
      milestones: [],
    },
    {
      id: "collision-avoidance",
      title: "Collision Avoidance",
      tickets: "",
      section: "q4",
      assigneeId: "j",
      notes: "Design creation and approval, ongoing by Jason.",
      bars: [
        {
          kind: "design",
          label: "Design Creation and Approval (Ongoing by Jason)",
          start: "2026-09-07",
          end: "2026-10-16",
        },
      ],
      milestones: [],
    },
    {
      id: "analytics-report-builder",
      title: "Analytics Report Builder",
      tickets: "",
      section: "q4",
      assigneeId: "b",
      notes: "Follows Analytics Suite exploration.",
      bars: [
        {
          kind: "design",
          label: "Design Creation and Approval",
          start: "2026-09-21",
          end: "2026-10-16",
        },
      ],
      milestones: [],
    },
    {
      id: "conjunction-assessment",
      title: "Conjunction Assessment as a Service",
      tickets: "",
      section: "q4",
      assigneeId: "e",
      notes: "",
      bars: [
        {
          kind: "design",
          label: "Design Creation and Approval",
          start: "2026-09-21",
          end: "2026-10-16",
        },
      ],
      milestones: [],
    },
    {
      id: "add-to-cart",
      title: "Add to cart functionality",
      tickets: "",
      section: "q4",
      assigneeId: "e",
      notes: "Need to talk to Rich/Duncan about this as a new feature on the roadmap.",
      bars: [
        {
          kind: "design",
          label: "Design Creation and Approval",
          start: "2026-09-28",
          end: "2026-10-16",
        },
      ],
      milestones: [],
    },
  ],
  stickies: [
    { id: "hack-1", label: "HACKATHON??", date: "2026-08-31", section: "explorations" },
    { id: "hack-2", label: "HACKATHON??", date: "2026-09-14", section: "explorations" },
  ],
  collapsed: {},
};
